#***********************************************************
#
#	Simple Makefile for Copymask and other tools
#
#
#
#***********************************************************

CC = gcc

default:
	gcc CopyRom.c -o CopyRom

